# Generated by Django 3.1.4 on 2021-04-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_recipe.recipe'),
        ),
    ]
